-- Development Seed Data: All Provider Services
-- This file seeds provider services for all providers across all categories
-- USE ONLY ON kuddl-dev DATABASE

-- Adventure Category Services

-- Priya Sharma (Event Planner) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_adv_001_001', 'prov_adv_001', 'adventure_kids_parties', 'cat_adventure',
 'Premium Birthday Party Planning',
 'Complete birthday party planning service including theme selection, vendor coordination, and on-day management.',
 15000, 240, 'home_visit',
 '["400001", "400002", "400003", "400004", "400005"]',
 3, 12, 50,
 '{"items": ["Party venue", "Guest count"], "included": ["Planning", "Coordination"]}',
 '["https://dev-assets.kuddl.co/services/party-1.jpg"]',
 true),

('ps_adv_001_002', 'prov_adv_001', 'adventure_events_and_celebrations', 'cat_adventure',
 'Festival & Special Occasion Events',
 'Specialized event planning for festivals, baby showers, and naming ceremonies.',
 20000, 300, 'home_visit',
 '["400001", "400002", "400003"]',
 0, 15, 100,
 '{"items": ["Event space"], "included": ["Theme development", "Vendor management"]}',
 '["https://dev-assets.kuddl.co/services/festival-1.jpg"]',
 true),

('ps_adv_001_003', 'prov_adv_001', 'adventure_party_decor_setups', 'cat_adventure',
 'Themed Party Decoration Consultation',
 'Expert consultation service for party decoration planning.',
 3000, 60, 'online',
 '["all"]',
 1, 18, 1,
 '{"items": ["Party theme"], "included": ["Consultation", "Plan document"]}',
 '["https://dev-assets.kuddl.co/services/decor-1.jpg"]',
 true),

('ps_adv_001_004', 'prov_adv_001', 'adventure_kids_parties', 'cat_adventure',
 'Luxury Kids Party Experience',
 'Ultra-premium party planning service with exclusive themes.',
 50000, 360, 'home_visit',
 '["400001", "400002"]',
 4, 14, 30,
 '{"items": ["Premium venue"], "included": ["Luxury decorations", "Entertainment"]}',
 '["https://dev-assets.kuddl.co/services/luxury-1.jpg"]',
 true),

('ps_adv_001_005', 'prov_adv_001', 'adventure_kids_parties', 'cat_adventure',
 'Interactive Game Stations Setup',
 'Professional setup of multiple interactive game stations.',
 8000, 180, 'home_visit',
 '["400001", "400002", "400003"]',
 5, 13, 40,
 '{"items": ["Open space"], "included": ["Game stations", "Facilitators"]}',
 '["https://dev-assets.kuddl.co/services/games-1.jpg"]',
 true);

-- Rahul Mehta (Decorator) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_adv_002_001', 'prov_adv_002', 'adventure_party_decor_setups', 'cat_adventure',
 'Premium Balloon Decoration Package',
 'Stunning balloon decoration including arches, columns, and centerpieces.',
 12000, 180, 'home_visit',
 '["400001", "400002", "400003"]',
 1, 18, 100,
 '{"items": ["Venue access"], "included": ["Balloon arch", "Columns"]}',
 '["https://dev-assets.kuddl.co/services/balloon-1.jpg"]',
 true),

('ps_adv_002_002', 'prov_adv_002', 'adventure_party_decor_setups', 'cat_adventure',
 'Themed Party Decoration - Full Setup',
 'Complete themed decoration for Unicorn, Superhero, Princess themes.',
 18000, 240, 'home_visit',
 '["400001", "400002"]',
 2, 14, 80,
 '{"items": ["Theme selection"], "included": ["Backdrop", "Table setup"]}',
 '["https://dev-assets.kuddl.co/services/theme-1.jpg"]',
 true),

('ps_adv_002_003', 'prov_adv_002', 'adventure_kids_parties', 'cat_adventure',
 'Birthday Party Decoration - Basic Package',
 'Affordable decoration package for intimate celebrations.',
 6000, 120, 'home_visit',
 '["400001", "400002", "400003", "400004"]',
 1, 15, 30,
 '{"items": ["Color preferences"], "included": ["Banner", "Balloons"]}',
 '["https://dev-assets.kuddl.co/services/basic-1.jpg"]',
 true),

('ps_adv_002_004', 'prov_adv_002', 'adventure_events_and_celebrations', 'cat_adventure',
 'Baby Shower Decoration',
 'Elegant decoration for baby shower celebrations.',
 15000, 180, 'home_visit',
 '["400001", "400002"]',
 0, 0, 60,
 '{"items": ["Theme preference"], "included": ["Backdrop", "Florals"]}',
 '["https://dev-assets.kuddl.co/services/baby-shower-1.jpg"]',
 true),

('ps_adv_002_005', 'prov_adv_002', 'adventure_party_decor_setups', 'cat_adventure',
 'Luxury Event Decoration with Florals',
 'Premium decoration with fresh florals and elegant draping.',
 35000, 300, 'home_visit',
 '["400001", "400002"]',
 0, 18, 100,
 '{"items": ["Premium venue"], "included": ["Florals", "Lighting"]}',
 '["https://dev-assets.kuddl.co/services/luxury-decor-1.jpg"]',
 true);

-- Bloom Category Services

-- Neha Kapoor (Music Teacher) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_bloom_001_001', 'prov_bloom_001', 'bloom_music_classes', 'cat_bloom',
 'Piano & Keyboard Classes for Beginners',
 'Structured piano lessons for children starting their musical journey.',
 2000, 60, 'center',
 '["400001", "400002"]',
 4, 12, 1,
 '{"items": ["Keyboard at home"], "included": ["4 weekly sessions", "Materials"]}',
 '["https://dev-assets.kuddl.co/services/piano-1.jpg"]',
 true),

('ps_bloom_001_002', 'prov_bloom_001', 'bloom_music_classes', 'cat_bloom',
 'Group Music Classes - Keyboard Ensemble',
 'Fun group keyboard classes for children.',
 1200, 60, 'center',
 '["400001", "400002"]',
 5, 10, 6,
 '{"items": ["Own keyboard"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/group-music-1.jpg"]',
 true),

('ps_bloom_001_003', 'prov_bloom_001', 'bloom_music_classes', 'cat_bloom',
 'Vocal Music & Singing Classes',
 'Individual vocal training for children.',
 1800, 45, 'center',
 '["400001", "400002"]',
 6, 14, 1,
 '{"items": ["Interest in singing"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/vocal-1.jpg"]',
 true),

('ps_bloom_001_004', 'prov_bloom_001', 'bloom_kids_classes_for_brain_development', 'cat_bloom',
 'Music for Brain Development',
 'Music program for cognitive development.',
 2500, 45, 'center',
 '["400001", "400002"]',
 3, 6, 8,
 '{"items": ["Parent involvement"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/brain-music-1.jpg"]',
 true),

('ps_bloom_001_005', 'prov_bloom_001', 'bloom_music_classes', 'cat_bloom',
 'Advanced Piano - Grade Preparation',
 'Intensive piano training for grade examinations.',
 3500, 90, 'center',
 '["400001", "400002"]',
 8, 16, 1,
 '{"items": ["Prior experience"], "included": ["4 weekly sessions", "Mock exams"]}',
 '["https://dev-assets.kuddl.co/services/advanced-piano-1.jpg"]',
 true);

-- Amit Patel (Sports Coach) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_bloom_002_001', 'prov_bloom_002', 'bloom_sports_coaching', 'cat_bloom',
 'Football Coaching - Beginner to Intermediate',
 'Comprehensive football training.',
 2500, 90, 'center',
 '["400001", "400002"]',
 6, 14, 15,
 '{"items": ["Sports shoes"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/football-1.jpg"]',
 true),

('ps_bloom_002_002', 'prov_bloom_002', 'bloom_sports_coaching', 'cat_bloom',
 'Cricket Coaching Academy',
 'Professional cricket coaching.',
 3000, 90, 'center',
 '["400001", "400002"]',
 7, 15, 12,
 '{"items": ["Cricket kit"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/cricket-1.jpg"]',
 true),

('ps_bloom_002_003', 'prov_bloom_002', 'bloom_sports_coaching', 'cat_bloom',
 'Athletics & Track Training',
 'Track and field training.',
 2000, 60, 'center',
 '["400001", "400002"]',
 8, 16, 20,
 '{"items": ["Running shoes"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/athletics-1.jpg"]',
 true),

('ps_bloom_002_004', 'prov_bloom_002', 'bloom_developmental_classes', 'cat_bloom',
 'Multi-Sport Development Program',
 'Exposure to multiple sports.',
 2800, 75, 'center',
 '["400001", "400002"]',
 5, 10, 15,
 '{"items": ["Sports shoes"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/multi-sport-1.jpg"]',
 true),

('ps_bloom_002_005', 'prov_bloom_002', 'bloom_sports_coaching', 'cat_bloom',
 'Personal Sports Training',
 'One-on-one sports coaching.',
 4000, 60, 'center',
 '["400001", "400002"]',
 6, 16, 1,
 '{"items": ["Sport preference"], "included": ["4 weekly sessions"]}',
 '["https://dev-assets.kuddl.co/services/personal-sports-1.jpg"]',
 true);

-- Care Category Services

-- Dr. Meera Iyer (Physiotherapist) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_care_001_001', 'prov_care_001', 'care_physiotherapy', 'cat_care',
 'Pediatric Physiotherapy - Home Visit',
 'Comprehensive physiotherapy for children.',
 1500, 60, 'home_visit',
 '["400001", "400002"]',
 0, 18, 1,
 '{"items": ["Medical history"], "included": ["Assessment", "Treatment"]}',
 '["https://dev-assets.kuddl.co/services/physio-1.jpg"]',
 true),

('ps_care_001_002', 'prov_care_001', 'care_physiotherapy', 'cat_care',
 'Pediatric Physiotherapy - Clinic Sessions',
 'Clinic-based physiotherapy.',
 1200, 45, 'center',
 '["400001", "400002"]',
 0, 18, 1,
 '{"items": ["Medical reports"], "included": ["Equipment usage"]}',
 '["https://dev-assets.kuddl.co/services/physio-clinic-1.jpg"]',
 true),

('ps_care_001_003', 'prov_care_001', 'care_pediatric_occupational_therapy_ot_', 'cat_care',
 'Occupational Therapy for Children',
 'OT focusing on fine motor skills.',
 1400, 60, 'home_visit',
 '["400001", "400002"]',
 2, 16, 1,
 '{"items": ["Specific concerns"], "included": ["Assessment", "Activities"]}',
 '["https://dev-assets.kuddl.co/services/ot-1.jpg"]',
 true),

('ps_care_001_004', 'prov_care_001', 'care_therapy_clinical_support', 'cat_care',
 'Sensory Integration Therapy',
 'Therapy for sensory processing difficulties.',
 1600, 60, 'center',
 '["400001", "400002"]',
 3, 12, 1,
 '{"items": ["Sensory concerns"], "included": ["Activities", "Equipment"]}',
 '["https://dev-assets.kuddl.co/services/sensory-1.jpg"]',
 true),

('ps_care_001_005', 'prov_care_001', 'care_therapy_clinical_support', 'cat_care',
 'Developmental Assessment & Screening',
 'Comprehensive developmental assessment.',
 2500, 90, 'center',
 '["400001", "400002"]',
 0, 6, 1,
 '{"items": ["Developmental history"], "included": ["Assessment", "Report"]}',
 '["https://dev-assets.kuddl.co/services/dev-assessment-1.jpg"]',
 true);

-- Sanjay Kumar (Speech Therapist) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_care_002_001', 'prov_care_002', 'care_speech_therapy', 'cat_care',
 'Speech & Language Therapy',
 'One-on-one speech therapy.',
 1500, 45, 'home_visit',
 '["400001", "400002"]',
 2, 16, 1,
 '{"items": ["Assessment report"], "included": ["Therapy", "Materials"]}',
 '["https://dev-assets.kuddl.co/services/speech-1.jpg"]',
 true),

('ps_care_002_002', 'prov_care_002', 'care_speech_therapy', 'cat_care',
 'Speech & Language Assessment',
 'Detailed evaluation of speech.',
 2000, 90, 'center',
 '["400001", "400002"]',
 2, 18, 1,
 '{"items": ["Developmental history"], "included": ["Assessment", "Report"]}',
 '["https://dev-assets.kuddl.co/services/speech-assessment-1.jpg"]',
 true),

('ps_care_002_003', 'prov_care_002', 'care_therapy_clinical_support', 'cat_care',
 'Feeding & Swallowing Therapy',
 'Therapy for feeding difficulties.',
 1600, 60, 'home_visit',
 '["400001", "400002"]',
 0, 10, 1,
 '{"items": ["Feeding history"], "included": ["Exercises", "Strategies"]}',
 '["https://dev-assets.kuddl.co/services/feeding-1.jpg"]',
 true),

('ps_care_002_004', 'prov_care_002', 'care_special_education_early_intervention', 'cat_care',
 'Early Intervention - Communication',
 'Early intervention for toddlers.',
 1400, 45, 'home_visit',
 '["400001", "400002"]',
 1, 4, 1,
 '{"items": ["Daily routine"], "included": ["Play therapy", "Coaching"]}',
 '["https://dev-assets.kuddl.co/services/early-intervention-1.jpg"]',
 true),

('ps_care_002_005', 'prov_care_002', 'care_speech_therapy', 'cat_care',
 'Social Communication Skills Training',
 'Pragmatic language skills therapy.',
 1500, 60, 'center',
 '["400001", "400002"]',
 4, 14, 1,
 '{"items": ["Social concerns"], "included": ["Activities", "Role-playing"]}',
 '["https://dev-assets.kuddl.co/services/social-comm-1.jpg"]',
 true);

-- Discover Category Services

-- Sneha Gupta (Workshop Facilitator) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_disc_001_001', 'prov_disc_001', 'discover_workshops_events', 'cat_discover',
 'STEM Workshop - Science Experiments',
 'Hands-on science workshop.',
 800, 120, 'center',
 '["400001", "400002"]',
 7, 14, 20,
 '{"items": ["Curiosity"], "included": ["Experiments", "Materials"]}',
 '["https://dev-assets.kuddl.co/services/stem-1.jpg"]',
 true),

('ps_disc_001_002', 'prov_disc_001', 'discover_workshops_events', 'cat_discover',
 'Robotics & Coding Workshop',
 'Introduction to robotics and coding.',
 1200, 150, 'center',
 '["400001", "400002"]',
 8, 15, 15,
 '{"items": ["No experience needed"], "included": ["Robot building", "Coding"]}',
 '["https://dev-assets.kuddl.co/services/robotics-1.jpg"]',
 true),

('ps_disc_001_003', 'prov_disc_001', 'discover_workshops_events', 'cat_discover',
 'Nature Exploration Workshop',
 'Outdoor learning experience.',
 600, 90, 'center',
 '["400001", "400002"]',
 6, 12, 25,
 '{"items": ["Outdoor clothing"], "included": ["Activities", "Journal"]}',
 '["https://dev-assets.kuddl.co/services/nature-1.jpg"]',
 true),

('ps_disc_001_004', 'prov_disc_001', 'discover_workshops_events', 'cat_discover',
 'Creative Writing Workshop',
 'Storytelling and creative writing.',
 700, 120, 'center',
 '["400001", "400002"]',
 8, 14, 15,
 '{"items": ["Notebook"], "included": ["Activities", "Mini-book"]}',
 '["https://dev-assets.kuddl.co/services/writing-1.jpg"]',
 true),

('ps_disc_001_005', 'prov_disc_001', 'discover_workshops_events', 'cat_discover',
 'Astronomy & Space Exploration',
 'Journey through the cosmos.',
 900, 120, 'center',
 '["400001", "400002"]',
 9, 16, 20,
 '{"items": ["Interest in space"], "included": ["Telescope", "Planetarium"]}',
 '["https://dev-assets.kuddl.co/services/astronomy-1.jpg"]',
 true);

-- Arjun Malhotra (Camp Organizer) - 5 services
INSERT OR REPLACE INTO provider_services (
    id, provider_id, subcategory_id, category_id,
    title, description, price, duration_minutes, location_type,
    service_area, age_group_min, age_group_max, max_participants,
    requirements, images, is_active
) VALUES
('ps_disc_002_001', 'prov_disc_002', 'discover_camps_holiday_programs', 'cat_discover',
 'Weekend Adventure Camp',
 'Action-packed weekend camp.',
 3500, 1440, 'center',
 '["400001", "400002"]',
 10, 16, 30,
 '{"items": ["Medical fitness"], "included": ["Activities", "Meals"]}',
 '["https://dev-assets.kuddl.co/services/adventure-camp-1.jpg"]',
 true),

('ps_disc_002_002', 'prov_disc_002', 'discover_camps_holiday_programs', 'cat_discover',
 'Summer Day Camp - Weekly Program',
 'Full-day summer camp.',
 5000, 480, 'center',
 '["400001", "400002"]',
 6, 14, 40,
 '{"items": ["Lunch box"], "included": ["Activities", "Snacks"]}',
 '["https://dev-assets.kuddl.co/services/summer-camp-1.jpg"]',
 true),

('ps_disc_002_003', 'prov_disc_002', 'discover_camps_holiday_programs', 'cat_discover',
 'Multi-Sport Holiday Camp',
 'Intensive sports camp.',
 4000, 480, 'center',
 '["400001", "400002"]',
 8, 16, 35,
 '{"items": ["Sports attire"], "included": ["Training", "Lunch"]}',
 '["https://dev-assets.kuddl.co/services/sports-camp-1.jpg"]',
 true),

('ps_disc_002_004', 'prov_disc_002', 'discover_camps_holiday_programs', 'cat_discover',
 'Leadership & Life Skills Camp',
 'Leadership development camp.',
 4500, 720, 'center',
 '["400001", "400002"]',
 11, 17, 25,
 '{"items": ["Open mind"], "included": ["Workshops", "Challenges"]}',
 '["https://dev-assets.kuddl.co/services/leadership-camp-1.jpg"]',
 true),

('ps_disc_002_005', 'prov_disc_002', 'discover_community_social_activities', 'cat_discover',
 'Community Service Project',
 'Meaningful community service.',
 500, 180, 'center',
 '["400001", "400002"]',
 9, 17, 30,
 '{"items": ["Parent consent"], "included": ["Activity", "Transportation"]}',
 '["https://dev-assets.kuddl.co/services/community-1.jpg"]',
 true);
