-- Development Seed Data: Services with Provider IDs
-- This file seeds actual services linked to providers
-- Each provider has 5-7 services across different subcategories
-- USE ONLY ON kuddl-dev DATABASE

-- Priya Sharma (Event Planner) - prov_adv_001 - 7 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_adv_001_001', 'prov_adv_001', 'adventure_kids_parties', 'Premium Birthday Party Planning', 'premium-birthday-party-planning-priya', 'Complete birthday party planning service including theme selection, vendor coordination, and on-day management. We handle everything from invitations to thank you notes.', 'Full-service birthday party planning', '₹15,000 - ₹25,000', '4-5 hours', '3-12 years', '{"items": ["Party venue", "Guest count 7 days prior"], "included": ["Planning consultation", "Vendor coordination", "Day-of management"]}', true, 1),

('srv_adv_001_002', 'prov_adv_001', 'adventure_events_and_celebrations', 'Festival & Special Occasion Events', 'festival-special-occasion-events-priya', 'Specialized event planning for festivals, baby showers, naming ceremonies. Cultural sensitivity and attention to detail ensure your celebration reflects your traditions.', 'Festival and special occasion planning', '₹20,000 - ₹35,000', '5-6 hours', '0-15 years', '{"items": ["Event space", "Cultural requirements"], "included": ["Theme development", "Vendor management", "Timeline creation"]}', true, 1),

('srv_adv_001_003', 'prov_adv_001', 'adventure_party_decor_setups', 'Party Decoration Consultation', 'party-decoration-consultation-priya', 'Expert consultation for party decoration planning. Get professional advice on themes, color schemes, and budget-friendly options.', 'Professional decoration consultation', '₹3,000 - ₹5,000', '1 hour', '1-18 years', '{"items": ["Party theme idea", "Budget"], "included": ["Video consultation", "Decoration plan", "Shopping list"]}', true, 1),

('srv_adv_001_004', 'prov_adv_001', 'adventure_entertainment_live_performers', 'Entertainment Coordination Service', 'entertainment-coordination-priya', 'We coordinate and book professional entertainers for your party - magicians, dancers, musicians, and more.', 'Entertainment booking and coordination', '₹8,000 - ₹15,000', '3-4 hours', '3-14 years', '{"items": ["Entertainment preferences", "Party schedule"], "included": ["Entertainer booking", "Coordination", "Backup arrangements"]}', true, 1),

('srv_adv_001_005', 'prov_adv_001', 'adventure_games_interaction_zones', 'Interactive Game Stations', 'interactive-game-stations-priya', 'Professional setup of multiple game stations with facilitators to keep children engaged throughout the party.', 'Multiple game stations with hosts', '₹8,000 - ₹12,000', '2-3 hours', '5-13 years', '{"items": ["Open space", "Guest count"], "included": ["5-7 game stations", "Facilitators", "All equipment", "Prizes"]}', true, 1),

('srv_adv_001_006', 'prov_adv_001', 'adventure_other', 'Kids Party Catering Coordination', 'kids-party-catering-priya', 'Coordinate kid-friendly catering with trusted vendors. Menu planning for children and adults with dietary considerations.', 'Party catering coordination', '₹10,000 - ₹20,000', '3-4 hours', '1-15 years', '{"items": ["Guest count", "Dietary restrictions"], "included": ["Menu planning", "Vendor coordination", "Setup supervision"]}', true, 1),

('srv_adv_001_007', 'prov_adv_001', 'adventure_cakes_return_gifts', 'Custom Return Gifts Planning', 'custom-return-gifts-priya', 'Curated return gift selection and coordination. Age-appropriate, budget-friendly options that guests will love.', 'Return gift planning and sourcing', '₹5,000 - ₹15,000', '2-3 hours', '1-14 years', '{"items": ["Budget per gift", "Guest count"], "included": ["Gift selection", "Sourcing", "Packaging coordination"]}', true, 1);

-- Rahul Mehta (Decorator) - prov_adv_002 - 6 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_adv_002_001', 'prov_adv_002', 'adventure_party_decor_setups', 'Premium Balloon Decoration', 'premium-balloon-decoration-rahul', 'Stunning balloon decoration including arches, columns, centerpieces, and themed sculptures. Premium quality balloons in your chosen colors.', 'Premium balloon decoration package', '₹12,000 - ₹18,000', '3-4 hours', '1-18 years', '{"items": ["Venue access 4 hours before", "Color scheme"], "included": ["Balloon arch", "Columns", "Centerpieces", "Setup"]}', true, 2),

('srv_adv_002_002', 'prov_adv_002', 'adventure_party_decor_setups', 'Themed Party Decoration', 'themed-party-decoration-rahul', 'Complete themed decoration for Unicorn, Superhero, Princess, Jungle Safari themes. Includes backdrop, table setup, and photo booth.', 'Full themed decoration setup', '₹18,000 - ₹25,000', '4-5 hours', '2-14 years', '{"items": ["Theme selection", "Venue dimensions"], "included": ["Backdrop", "Table decor", "Ceiling hangings", "Photo booth"]}', true, 2),

('srv_adv_002_003', 'prov_adv_002', 'adventure_kids_parties', 'Birthday Decoration - Basic', 'birthday-decoration-basic-rahul', 'Affordable decoration package for intimate celebrations. Essential decorations to make your party festive and photo-ready.', 'Basic birthday decoration package', '₹6,000 - ₹10,000', '2-3 hours', '1-15 years', '{"items": ["Color preferences", "Venue access"], "included": ["Banner", "Balloons", "Table centerpiece", "Cake table decor"]}', true, 2),

('srv_adv_002_004', 'prov_adv_002', 'adventure_events_and_celebrations', 'Baby Shower Decoration', 'baby-shower-decoration-rahul', 'Elegant decoration for baby shower celebrations. Gender-neutral or gender-specific themes with sophisticated styling.', 'Baby shower decoration service', '₹15,000 - ₹22,000', '3-4 hours', '0-0 years', '{"items": ["Theme preference", "Venue access"], "included": ["Backdrop", "Floral arrangements", "Table decor", "Signage"]}', true, 2),

('srv_adv_002_005', 'prov_adv_002', 'adventure_premium_experience_add_ons', 'Luxury Event Decoration', 'luxury-event-decoration-rahul', 'Premium decoration with fresh florals, elegant draping, custom backdrops, and professional lighting for upscale events.', 'Luxury decoration with florals', '₹35,000 - ₹50,000', '5-6 hours', '0-18 years', '{"items": ["Premium venue", "Design consultation"], "included": ["Fresh florals", "Custom backdrop", "Lighting", "Draping"]}', true, 2),

('srv_adv_002_006', 'prov_adv_002', 'adventure_photographers', 'Event Photography Coordination', 'event-photography-coordination-rahul', 'Coordinate professional photographers for your event. We work with trusted photographers to capture your special moments.', 'Photography coordination service', '₹8,000 - ₹15,000', '3-4 hours', '0-18 years', '{"items": ["Event schedule", "Photography preferences"], "included": ["Photographer booking", "Shot list coordination", "Delivery coordination"]}', true, 2);

-- Neha Kapoor (Music Teacher) - prov_bloom_001 - 6 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_bloom_001_001', 'prov_bloom_001', 'bloom_music_classes', 'Piano & Keyboard Classes', 'piano-keyboard-classes-neha', 'Structured piano/keyboard lessons for beginners. Focus on proper technique, music theory basics, and playing simple songs.', 'Beginner piano and keyboard lessons', '₹2,000 - ₹3,000/month', '1 hour/session', '4-12 years', '{"items": ["Keyboard at home for practice", "Weekly attendance"], "included": ["4 weekly sessions", "Practice materials", "Progress tracking"]}', true, 3),

('srv_bloom_001_002', 'prov_bloom_001', 'bloom_music_classes', 'Group Music Classes', 'group-music-classes-neha', 'Fun group keyboard classes where children learn together. Focus on rhythm, coordination, and playing in harmony.', 'Group keyboard ensemble classes', '₹1,200 - ₹1,800/month', '1 hour/session', '5-10 years', '{"items": ["Own keyboard", "Regular attendance"], "included": ["4 weekly sessions", "Group practice", "Performance opportunities"]}', true, 3),

('srv_bloom_001_003', 'prov_bloom_001', 'bloom_music_classes', 'Vocal Music & Singing', 'vocal-music-singing-neha', 'Individual vocal training focusing on voice modulation, breathing techniques, and singing popular songs.', 'Vocal training and singing lessons', '₹1,800 - ₹2,500/month', '45 min/session', '6-14 years', '{"items": ["Interest in singing", "Practice commitment"], "included": ["4 weekly sessions", "Voice training", "Song practice"]}', true, 3),

('srv_bloom_001_004', 'prov_bloom_001', 'bloom_kids_classes_for_brain_development', 'Music for Brain Development', 'music-brain-development-neha', 'Music program for young children focusing on cognitive development through rhythm games and simple instruments.', 'Early childhood music program', '₹2,500 - ₹3,500/month', '45 min/session', '3-6 years', '{"items": ["Parent involvement for younger kids"], "included": ["4 weekly sessions", "Age-appropriate instruments", "Musical games"]}', true, 3),

('srv_bloom_001_005', 'prov_bloom_001', 'bloom_music_classes', 'Advanced Piano - Grade Prep', 'advanced-piano-grade-prep-neha', 'Intensive piano training for students preparing for Trinity, ABRSM, or other music grade examinations.', 'Piano grade examination preparation', '₹3,500 - ₹5,000/month', '1.5 hours/session', '8-16 years', '{"items": ["Prior piano experience", "Own piano/keyboard"], "included": ["4 weekly sessions", "Exam syllabus", "Mock exams", "Theory"]}', true, 3),

('srv_bloom_001_006', 'prov_bloom_001', 'bloom_kids_learning_programmes', 'Music Theory Classes', 'music-theory-classes-neha', 'Comprehensive music theory education covering notation, scales, chords, and composition basics.', 'Music theory and notation', '₹1,500 - ₹2,000/month', '1 hour/session', '7-16 years', '{"items": ["Basic music knowledge helpful"], "included": ["4 weekly sessions", "Theory workbook", "Practice exercises"]}', true, 3);

-- Amit Patel (Sports Coach) - prov_bloom_002 - 7 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_bloom_002_001', 'prov_bloom_002', 'bloom_sports_coaching', 'Football Coaching', 'football-coaching-amit', 'Comprehensive football training covering dribbling, passing, shooting, and game tactics. Separate batches for different age groups.', 'Football skills training', '₹2,500 - ₹3,500/month', '1.5 hours/session', '6-14 years', '{"items": ["Sports shoes", "Water bottle"], "included": ["4 weekly sessions", "Football provided", "Fitness training", "Mini tournaments"]}', true, 4),

('srv_bloom_002_002', 'prov_bloom_002', 'bloom_sports_coaching', 'Cricket Coaching', 'cricket-coaching-amit', 'Professional cricket coaching for all skill levels. Batting, bowling, fielding techniques with match strategies.', 'Cricket skills development', '₹3,000 - ₹4,000/month', '1.5 hours/session', '7-15 years', '{"items": ["Cricket kit (can be provided initially)"], "included": ["4 weekly sessions", "Batting practice", "Bowling techniques", "Match practice"]}', true, 4),

('srv_bloom_002_003', 'prov_bloom_002', 'bloom_sports_coaching', 'Athletics & Track Training', 'athletics-track-training-amit', 'Track and field training including running techniques, long jump, high jump. Builds speed, stamina, and athletic ability.', 'Athletics and track training', '₹2,000 - ₹3,000/month', '1 hour/session', '8-16 years', '{"items": ["Running shoes", "Athletic wear"], "included": ["4 weekly sessions", "Running drills", "Technique training", "Timing"]}', true, 4),

('srv_bloom_002_004', 'prov_bloom_002', 'bloom_developmental_classes', 'Multi-Sport Development', 'multi-sport-development-amit', 'Exposure to multiple sports including football, cricket, basketball. Helps children discover interests and develop overall athleticism.', 'Multi-sport exposure program', '₹2,800 - ₹3,800/month', '1.5 hours/session', '5-10 years', '{"items": ["Sports shoes", "Comfortable clothing"], "included": ["4 weekly sessions", "4 different sports", "Basic skills", "Team games"]}', true, 4),

('srv_bloom_002_005', 'prov_bloom_002', 'bloom_sports_coaching', 'Personal Sports Training', 'personal-sports-training-amit', 'One-on-one sports coaching tailored to specific goals. Can focus on single sport or multiple sports with personalized attention.', 'Individual sports coaching', '₹4,000 - ₹6,000/month', '1 hour/session', '6-16 years', '{"items": ["Sport preference", "Specific goals"], "included": ["4 weekly sessions", "Customized plan", "Video analysis", "Progress tracking"]}', true, 4),

('srv_bloom_002_006', 'prov_bloom_002', 'bloom_sports_coaching', 'Basketball Coaching', 'basketball-coaching-amit', 'Basketball fundamentals including dribbling, shooting, passing, and team play. Indoor court training available.', 'Basketball skills training', '₹2,500 - ₹3,500/month', '1.5 hours/session', '7-15 years', '{"items": ["Sports shoes", "Comfortable clothing"], "included": ["4 weekly sessions", "Basketball provided", "Drills", "Game practice"]}', true, 4),

('srv_bloom_002_007', 'prov_bloom_002', 'bloom_developmental_classes', 'Kids Fitness Program', 'kids-fitness-program-amit', 'General fitness program for children focusing on strength, flexibility, and cardiovascular health through fun activities.', 'Children fitness and wellness', '₹2,200 - ₹3,000/month', '1 hour/session', '6-14 years', '{"items": ["Comfortable clothing", "Water bottle"], "included": ["4 weekly sessions", "Fitness activities", "Health tracking", "Nutrition guidance"]}', true, 4);

-- Dr. Meera Iyer (Physiotherapist) - prov_care_001 - 6 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_care_001_001', 'prov_care_001', 'care_physiotherapy', 'Pediatric Physiotherapy - Home', 'pediatric-physiotherapy-home-meera', 'Comprehensive physiotherapy for children with developmental delays, motor skill challenges, or post-injury rehabilitation at home.', 'Home visit physiotherapy', '₹1,500 - ₹2,000/session', '1 hour', '0-18 years', '{"items": ["Medical history", "Previous reports"], "included": ["Assessment", "Treatment", "Home exercise plan", "Parent guidance"]}', true, 5),

('srv_care_001_002', 'prov_care_001', 'care_physiotherapy', 'Pediatric Physiotherapy - Clinic', 'pediatric-physiotherapy-clinic-meera', 'Clinic-based physiotherapy with access to specialized equipment. Ideal for intensive therapy programs.', 'Clinic physiotherapy sessions', '₹1,200 - ₹1,800/session', '45 min', '0-18 years', '{"items": ["Comfortable clothing", "Medical reports"], "included": ["Equipment usage", "Specialized therapy", "Progress documentation"]}', true, 5),

('srv_care_001_003', 'prov_care_001', 'care_pediatric_occupational_therapy_ot_', 'Occupational Therapy', 'occupational-therapy-meera', 'OT focusing on fine motor skills, sensory processing, and activities of daily living for children.', 'Pediatric occupational therapy', '₹1,400 - ₹2,000/session', '1 hour', '2-16 years', '{"items": ["Specific concerns", "School reports if applicable"], "included": ["Skill assessment", "Therapeutic activities", "Parent training"]}', true, 5),

('srv_care_001_004', 'prov_care_001', 'care_therapy_clinical_support', 'Sensory Integration Therapy', 'sensory-integration-therapy-meera', 'Specialized therapy for children with sensory processing difficulties using play-based activities.', 'Sensory processing therapy', '₹1,600 - ₹2,200/session', '1 hour', '3-12 years', '{"items": ["Sensory profile if available"], "included": ["Sensory activities", "Therapeutic equipment", "Home strategies"]}', true, 5),

('srv_care_001_005', 'prov_care_001', 'care_therapy_clinical_support', 'Developmental Assessment', 'developmental-assessment-meera', 'Comprehensive assessment to identify delays in motor, cognitive, social, and communication skills.', 'Child development screening', '₹2,500 - ₹3,500/session', '1.5 hours', '0-6 years', '{"items": ["Developmental history", "Parent questionnaire"], "included": ["Standardized testing", "Detailed report", "Recommendations", "Consultation"]}', true, 5),

('srv_care_001_006', 'prov_care_001', 'care_physiotherapy', 'Sports Injury Rehabilitation', 'sports-injury-rehabilitation-meera', 'Rehabilitation program for children recovering from sports injuries. Gradual return to activity protocols.', 'Sports injury rehab for kids', '₹1,800 - ₹2,500/session', '1 hour', '8-18 years', '{"items": ["Injury details", "Medical clearance"], "included": ["Assessment", "Treatment plan", "Exercises", "Progress monitoring"]}', true, 5);

-- Sanjay Kumar (Speech Therapist) - prov_care_002 - 6 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_care_002_001', 'prov_care_002', 'care_speech_therapy', 'Speech & Language Therapy', 'speech-language-therapy-sanjay', 'One-on-one speech therapy for articulation disorders, language delays, stuttering, or voice disorders.', 'Individual speech therapy', '₹1,500 - ₹2,000/session', '45 min', '2-16 years', '{"items": ["Assessment report if available"], "included": ["Therapy activities", "Home practice materials", "Parent guidance"]}', true, 6),

('srv_care_002_002', 'prov_care_002', 'care_speech_therapy', 'Speech Assessment', 'speech-assessment-sanjay', 'Detailed evaluation of speech sound production, language comprehension, fluency, and voice quality.', 'Comprehensive speech evaluation', '₹2,000 - ₹3,000/session', '1.5 hours', '2-18 years', '{"items": ["Developmental history"], "included": ["Standardized tests", "Detailed report", "Treatment plan", "Consultation"]}', true, 6),

('srv_care_002_003', 'prov_care_002', 'care_therapy_clinical_support', 'Feeding & Swallowing Therapy', 'feeding-swallowing-therapy-sanjay', 'Specialized therapy for feeding difficulties, oral motor challenges, or swallowing disorders.', 'Feeding therapy for children', '₹1,600 - ₹2,200/session', '1 hour', '0-10 years', '{"items": ["Feeding history", "Medical clearance"], "included": ["Oral motor exercises", "Feeding strategies", "Parent training"]}', true, 6),

('srv_care_002_004', 'prov_care_002', 'care_special_education_early_intervention', 'Early Intervention - Communication', 'early-intervention-communication-sanjay', 'Early intervention for toddlers with communication delays. Play-based activities to build foundational skills.', 'Early communication intervention', '₹1,400 - ₹1,800/session', '45 min', '1-4 years', '{"items": ["Daily routine info"], "included": ["Play-based therapy", "Communication strategies", "Parent coaching"]}', true, 6),

('srv_care_002_005', 'prov_care_002', 'care_speech_therapy', 'Social Communication Skills', 'social-communication-skills-sanjay', 'Therapy for pragmatic language skills - turn-taking, topic maintenance, social cues, and conversation.', 'Social skills training', '₹1,500 - ₹2,000/session', '1 hour', '4-14 years', '{"items": ["Social communication concerns"], "included": ["Social skills activities", "Role-playing", "Video modeling", "Strategies"]}', true, 6),

('srv_care_002_006', 'prov_care_002', 'care_speech_therapy', 'Stuttering Therapy', 'stuttering-therapy-sanjay', 'Specialized therapy for children who stutter. Fluency shaping and stuttering modification techniques.', 'Stuttering treatment program', '₹1,600 - ₹2,200/session', '1 hour', '4-16 years', '{"items": ["Stuttering history"], "included": ["Fluency techniques", "Confidence building", "Parent education", "School liaison"]}', true, 6);

-- Sneha Gupta (Workshop Facilitator) - prov_disc_001 - 6 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_disc_001_001', 'prov_disc_001', 'discover_workshops_events', 'STEM Workshop - Science', 'stem-workshop-science-sneha', 'Hands-on science workshop with exciting experiments. Topics include chemistry, physics, and biology.', 'Science experiments workshop', '₹800 - ₹1,200/child', '2 hours', '7-14 years', '{"items": ["Curiosity and enthusiasm"], "included": ["Multiple experiments", "All materials", "Take-home kit", "Certificate"]}', true, 7),

('srv_disc_001_002', 'prov_disc_001', 'discover_workshops_events', 'Robotics & Coding Workshop', 'robotics-coding-workshop-sneha', 'Introduction to robotics and coding through hands-on projects. Build robots and learn basic programming.', 'Robotics and coding for kids', '₹1,200 - ₹1,800/child', '2.5 hours', '8-15 years', '{"items": ["No prior experience needed"], "included": ["Robot building", "Coding basics", "All equipment", "Certificate"]}', true, 7),

('srv_disc_001_003', 'prov_disc_001', 'discover_workshops_events', 'Nature Exploration Workshop', 'nature-exploration-workshop-sneha', 'Outdoor learning connecting children with nature. Plant identification, bird watching, and environmental awareness.', 'Outdoor nature workshop', '₹600 - ₹1,000/child', '1.5 hours', '6-12 years', '{"items": ["Outdoor clothing", "Hat and water"], "included": ["Nature activities", "Guided exploration", "Nature journal", "Eco-craft"]}', true, 7),

('srv_disc_001_004', 'prov_disc_001', 'discover_workshops_events', 'Creative Writing Workshop', 'creative-writing-workshop-sneha', 'Unleash creativity through storytelling and writing. Learn story structure, character development, and descriptive writing.', 'Writing and storytelling workshop', '₹700 - ₹1,000/child', '2 hours', '8-14 years', '{"items": ["Notebook and pen"], "included": ["Writing activities", "Storytelling games", "Creative exercises", "Mini-book"]}', true, 7),

('srv_disc_001_005', 'prov_disc_001', 'discover_workshops_events', 'Astronomy Workshop', 'astronomy-workshop-sneha', 'Journey through the cosmos! Learn about planets, stars, and space. Includes telescope observation and planetarium show.', 'Space and astronomy workshop', '₹900 - ₹1,500/child', '2 hours', '9-16 years', '{"items": ["Interest in space"], "included": ["Telescope session", "Planetarium show", "Activities", "Star map", "Certificate"]}', true, 7),

('srv_disc_001_006', 'prov_disc_001', 'discover_workshops_events', 'Art & Craft Workshop', 'art-craft-workshop-sneha', 'Hands-on art workshop exploring various mediums - painting, clay modeling, and mixed media crafts.', 'Creative arts workshop', '₹600 - ₹900/child', '2 hours', '5-12 years', '{"items": ["Apron or old clothes"], "included": ["All art materials", "Multiple projects", "Take-home creations", "Certificate"]}', true, 7);

-- Arjun Malhotra (Camp Organizer) - prov_disc_002 - 5 services
INSERT OR REPLACE INTO services (id, provider_id, subcategory_id, name, slug, description, short_description, price_range, duration, age_group, requirements, is_active, sort_order) VALUES
('srv_disc_002_001', 'prov_disc_002', 'discover_camps_holiday_programs', 'Weekend Adventure Camp', 'weekend-adventure-camp-arjun', 'Action-packed weekend camp with trekking, camping skills, team building, and nature exploration.', '2-day adventure camp', '₹3,500 - ₹5,000/child', '2 days', '10-16 years', '{"items": ["Medical fitness", "Parent consent"], "included": ["All activities", "Meals", "Camping equipment", "Safety gear", "Insurance"]}', true, 8),

('srv_disc_002_002', 'prov_disc_002', 'discover_camps_holiday_programs', 'Summer Day Camp', 'summer-day-camp-arjun', 'Full-day summer camp with sports, arts, science, and outdoor games. New theme each week!', 'Weekly summer day camp', '₹5,000 - ₹7,000/week', '5 days', '6-14 years', '{"items": ["Lunch box", "Water bottle"], "included": ["5 full days", "Multiple activities", "Snacks", "Showcase", "Certificate"]}', true, 8),

('srv_disc_002_003', 'prov_disc_002', 'discover_camps_holiday_programs', 'Multi-Sport Holiday Camp', 'multi-sport-holiday-camp-arjun', 'Intensive sports camp with training in football, cricket, basketball, and athletics. Professional coaching.', 'Sports holiday camp', '₹4,000 - ₹6,000/week', '5 days', '8-16 years', '{"items": ["Sports attire", "Own shoes"], "included": ["5-day program", "Multi-sport training", "Coaches", "Lunch", "Tournament"]}', true, 8),

('srv_disc_002_004', 'prov_disc_002', 'discover_camps_holiday_programs', 'Leadership Skills Camp', 'leadership-skills-camp-arjun', 'Specialized camp for leadership development, communication, problem-solving, and teamwork through activities and workshops.', 'Leadership development camp', '₹4,500 - ₹6,500/program', '3 days', '11-17 years', '{"items": ["Willingness to participate"], "included": ["3-day program", "Leadership workshops", "Team challenges", "Meals", "Certificate"]}', true, 8),

('srv_disc_002_005', 'prov_disc_002', 'discover_community_social_activities', 'Community Service Project', 'community-service-project-arjun', 'Meaningful community service for children. Environmental cleanup, charity activities, teaching empathy and social responsibility.', 'Community service for kids', '₹500 - ₹800/child', '3 hours', '9-17 years', '{"items": ["Parent consent"], "included": ["Community activity", "Transportation", "Supervision", "Refreshments", "Certificate"]}', true, 8);
